In [116]:
possible_moves = ["R", "P", "S"]
opponent_history = ["R", "S", "P", "R", "S", "P", "R", "S", "P", "R", "S", "P"]
player_history = ["P", "R", "S", "P", "R", "S", "P", "R", "S", "P", "R", "S"]

In [176]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [224]:
x = pd.DataFrame(list(zip(opponent_history[-5:], player_history[-5:])),
                    columns=["opponent_move", "player_move"])

In [225]:
print(x)

  opponent_move player_move
0             S           R
1             P           S
2             R           P
3             S           R
4             P           S


In [226]:
x = pd.get_dummies(x)

In [227]:
x_test = x.iloc[-1, :].values
x_test = np.array(x_test).reshape((1, 6))
x = x.iloc[:-1 , :]

In [228]:
print(x_test)

[[1 0 0 0 0 1]]


In [233]:
y = pd.DataFrame(opponent_history[-5:-1], 
        columns=["opponent_next_move"])

y = pd.get_dummies(y)

In [234]:
print(y)

   opponent_next_move_P  opponent_next_move_R  opponent_next_move_S
0                     0                     0                     1
1                     1                     0                     0
2                     0                     1                     0
3                     0                     0                     1


In [209]:
y_P = y.iloc[:, 0].values
y_R = y.iloc[:, 1].values
y_S = y.iloc[:, 2].values

In [174]:
print(y_P)

[0 1 0 0 1 0 0 1 0 0 1]


In [211]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
        
classifier.fit(x, y_P)
P_pred = classifier.predict_proba(x_test)

classifier.fit(x, y_R)
R_pred = classifier.predict_proba(x_test)

classifier.fit(x, y_S)
S_pred = classifier.predict_proba(x_test)

NameError: name 'most_likely' is not defined

In [213]:


def most_likely(P_pred, R_pred, S_pred):
    if (P_pred[0][1] > R_pred[0][1] and P_pred[0][1] > S_pred[0][1]):
        return "P"
    if (R_pred[0][1] > P_pred[0][1] and R_pred[0][1] > S_pred[0][1]):
        return "R"
    else:
        return "S"

In [219]:


P_pred[0][1]

0.15035830685477042

In [216]:
R_pred

array([[0.31222674, 0.68777326]])

In [217]:
S_pred

array([[0.84964169, 0.15035831]])